### ISSUE TITLE
reloader: implement directory rename on linux

### ISSUE THREAD

**Issue by kristoff-it** [kristoff-it/zine#4]
This is currently a `@panic("TODO")`.

It's necessary to understand how a `IN_MOVE` event will relate to watch fds of subdirectories in order to make this work correctly.

See `zine/server/Reloader.zig` for more info.

**Comment by MrDmitry** [comment]
@kristoff-it I'm prototyping a way to handle this and figured I'd clarify a couple of things on handling the move in general.

#### 1. Updating watched `dir_path`s
Only the updated inode generates the move, the event is not cascaded by `inotify` to all descendants. Since paths are stored in `watched_fds`, once parent directory is moved, the values for descendants would become invalid.
My gut tells me that a reverse lookup about **known** direct descendants solves the cascading update. So a hash map of `fd` as a key and an array list of direct descendant `fd`s. So a move itself can happen in 2 phases:
1. find your old parent (`IN_MOVE_FROM`) and remove yourself from its descendants
2. find your new parent (`IN_MOVE_TO`) and add yourself to its descendants
3. iterate over your descendants and cascade path update for them

**Alternatively**, the path could be calculated by storing an optional `parent` `fd` that would allow _name_ lookup for all watched nodes. This would require lookups each time a file's path is calculated, which should be a more common case than a move. So I feel like the reverse lookup and descendant tracking would be preferable.

#### 2. Calling `onXChange` for a directory 
When a directory is moved, it may have unwatched files in it. Reloader's `onXChange` currently ignores the given paths, so it's not clear to me how directories should be handled. Should they provide _"path and a directory name"_ just like a file move provides _"path and a file name"_, or should it somehow indicate that it actually is a directory? Maybe a separate method altogether that would be a direct proxy right now (and maybe in future would walk the directory and trigger update events for all files)?
For completeness, a move has (at least?) 2 `onXChange` events:
1. Old location is updated with content removed
2. New location is updated with content added

Current implementation doesn't consider old locations, and maybe that's intended as I can't find a good counter example case off the top of my head, but I still figured I'd clarify how `onXChange` should be handled for a directory.

#### 3. Handling the deletion
Not directly related to the move, but deletion currently is not handled for files (and I think that's okay), but for directories at the very least watchers should be removed.
I don't know if `onXChange` is needed (although for input files it could be even breaking), but a directory removal is cascaded. If any updates are to be propagated to the `Reloader`, there has to be some sort of debouncing or throttling of the events somewhere to avoid unnecessary side effects.
To clarify, this does not happen with the move, only with deletion.

**Comment by kristoff-it** [comment]
About point 1: 

Agreed on your main strategy. I think it's preferable over the alternative (reconstruct paths every time) because it's better to optimize for more common operations (a file being modified).

About point 2:

In our context the only situation where a directory move can happen is in an input directory (eg content/ or layouts/) and in such case we really don't care about the path because our reaction in any case is going to be to run `zig build`. I should improve that API to make it more focused on our actual use case. Please call onXChange with whatever values (empty string for the filename is fine too) and then I will give it a nice refactoring once we merge this.

About point 3:

Yes deletion needs to be handled! It's necessary to both call onXChange when a file changes and to do the bookkeeping correctly. Deleting an input file could change how other files are rendered (so we want to call `zig build`) and similarly we should trigger a reload of the page. Like for the previous point, if you implement the main feature, I will then take care to polish the behavior of onXChange for these cases.

> I don't know if onXChange is needed (although for input files it could be even breaking), but a directory removal is cascaded. If any updates are to be propagated to the Reloader, there has to be some sort of debouncing or throttling of the events somewhere to avoid unnecessary side effects.
> To clarify, this does not happen with the move, only with deletion.

Good point. I think implementing debouncing can be a follow-up that also depends on investigating a little what other OSs do in those cases. I'll open an issue for it once we close this issue.
