### ISSUE TITLE
Syntax error when evaluating chain

### ISSUE THREAD

**Issue by BrookJeynes** [kristoff-it/zine#42]
Repro: https://github.com/BrookJeynes/brookjeynes.dev-zine/tree/zine-syntax-error
Code in question: `layouts/templates/base.shtml:31`

![image](https://github.com/user-attachments/assets/0becec0b-92e5-48d0-995f-529bc72bbca6)

**Comment by kristoff-it** [comment]
Fixed in v0.2.0, please reopen if you can still reproduce the problem.

A couple notes for you:

1. While reproducing the error I noticed that maybe `contains` is more appropriate than `endsWith`, depending on what you want to achieve, just keep that in mind (I got confused for a while while testing because of that).
2. To upgrade to v0.2.0 see the latest changelog entry on the official zine website (or the updated docs)
