### ISSUE TITLE
Automatically include 'width' and 'height' properties on images

### ISSUE THREAD

**Issue by pfgithub** [kristoff-it/zine#63]
Images embedded with `$image` could have their width and height included by parsing the image file to extract its size.

This could be done using a library like wuffs ([example](https://github.com/pfgithub/blockeditor/blob/5bc483c6352a622b427cea5764e7b27117e807fe/packages/loadimage/src/loadimage.zig#L39-L72)) for many formats.

By setting the width and height of images, it prevents all the content of the page from shifting around when the image loads.

**Comment by kristoff-it** [comment]
How would that interact with other layouting things like css values? I'd be open to doing it if it were to not cause confusing behavior when users try to define styling in some other manner.

Alternatively we could add a builtin function, like `.autoSize()`, so that users can opt into this behavior. I'm not going to implement this myself but would merge a PR for it.

If you decide to implement it, here's a list of todos:

1. Package Wuffs for https://github.com/allyourcodebase (I can send you an invite to the org) using the pristine tarball method
2. Add to SuperMD (https://github.com/kristoff-it/supermd) a new builtin that sets a flag in `$image` when the user calls `.autoSize()` (assuming that defaulting to this behavior is confirmed to not be always straightforward for users, which I imagine is the most probable outcome). It's a bit metaprogramming-heavy but you can see plenty of other examples of how to generate a new builtin that sets a boolean field.
3. In Zine  (this repo) change `src/render/html.zig` to observe that flag and use wuffs to do the work.

**Comment by pfgithub** [comment]
In css, it requires a slight change. If you ever override the width of the image, you have to also override the height. ie `width: 50px` or `max-width: 100vw` in css will now squish the image, you have to add `height: auto`. This might cause horizontal image squishing for some people until they set `height: auto` on the image. Even with explicit sizes set in css, setting `width` and `height` on the image tag is still useful because of a fix in browsers two years ago ([more info](https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/)).

I can implement this but I'd prefer to try making it default (and maybe ignoring on error) rather than opt-in with `.autoSize()`. I would like an invite to allyourcodebase so I can add the package.

**Comment by kristoff-it** [comment]
Sorry for the delay in following up, I've just sent you an invite.

I'm open to try turning this on by default.

**Comment by pfgithub** [comment]
#88
