### ISSUE TITLE
How to add additional build step for css

### ISSUE THREAD

**Issue by dkotrada** [kristoff-it/zine#79]
I would add additional steps for generating my css. One for release and one for dev. 

How can I do it given those commands on cli?

Release
`deno run --allow-env --allow-read --allow-write npm:@unocss/cli "layouts/*.shtml" -o "assets/css/uno.css"`

Dev
`deno run --allow-env --allow-read --allow-write npm:@unocss/cli "layouts/*.shtml" --watch`

Or with bunx
`bunx @unocss/cli "layouts/*.shtml" -o "assets/css/uno.css"`

**Comment by kristoff-it** [comment]
You need to learn how to use the Zig build system.

As a starting point, you might want to do something like this:

```zig
const run_bun = b.addSystemCommand(&.{"bunx", "and", "other", "arguments"});
const output = run_bun.addOutputFile("uno.css");
// ...

zine.website(.{
  //...
  .build_assets = &.{
     .{
        .name = "uno.css",
        .lp = output,
        .install_path = "uno.css",
     },
  },
}); 

```

Note that I'm not sure this interface suports wildcard expansion, so you might need to write a shell script  if you want to maintain it, or walk the layouts directory to get an explicit list of files.

I'm also not sure what your tooling is supposed to be doing so I can't say for sure if I'm giving you optimal advice in order to achieve your end goal.
