### ISSUE TITLE
[feat] Optional `<super>` blocks

### ISSUE THREAD

**Issue by dubrowgn** [kristoff-it/zine#81]
## Problem

It's often handy to have an optional extension point in a template. If not specified, the contents of which would be empty. As far as I can tell, putting a `<super>` block in a zine template forces all consumers to specify its contents.

## Proposal

Allow optional `<super>` blocks. Perhaps with `<super?>` or `<super optional>`, etc.

**Comment by kristoff-it** [comment]
Not allowing template authors to implicitly drop extension points while implementing chains is by design.

Note that if you don't want to keep propagating an extension point, you can explicitly terminate it by not repeating the `super` tag again when fulfilling it.

```
// base.shtml
<title id="title"><super></title>

// ext1.shtml
<extends template="base.shtml>
<title id="title"></title>
```

With this setup, extending `ext1` will not require to define `title` anymore.

Finally, be aware that SuperHTML is currently missing a way to define "snippets", once those land maybe you will find that something you implemented as an extension chain, actually works better as a snippet.

**Comment by dubrowgn** [comment]
> Not allowing template authors to implicitly drop extension points while implementing chains is by design.

I appreciate how this is useful in many contexts, and I wouldn't want you to remove it, which is why I proposed alternate syntax.

> Note that if you don't want to keep propagating an extension point, you can explicitly terminate it by not repeating the super tag again when fulfilling it.

There are a lot of ways to work around the issue, it is true. I was just looking to reduce boilerplate for situations where you don't need strong guarantees. For my use case that seems to be most of the time, but it sounds like your use case is pretty different.

That being said, this is your show. Thanks for your time.

**Comment by kristoff-it** [comment]
> For my use case that seems to be most of the time, but it sounds like your use case is pretty different.

I don't have particularly large scale usecases, but I've come back to my own code enough times to not appreciate the shortcuts I myself used when implementing stuff the first time :^)

It's also an attitude that I've come to appreciate while working with Zig, for what that's worth.

I do genuinely think though that snippets will prove to be a more flexible tool that people should prefer over "extension" in Zine, once it becomes available, which is another reason why I'm keeping this system farily rigid.
